### ISSUE TITLE
Add Caveat:  HTTPS scripts are limited.

### ISSUE THREAD

**Issue by timbl** [w3ctag/web-https#12] opened 2014-12-26 11:00 UTC
The way the current world of browsers has been built is that HTTP scrips are given more power than HTTPS scripts.  Therefore, some scripts must be served over HTTP. 

An example is any mashup script which merges open data from many sources, one or more of which is  served over HTTP.

The logic from the browser maker seems to be that when the user is running a script which has the 's', the user expects to have a more secure situation.    Even though a script has been loaded securely, that script itself is not trusted to access non-secure content.   Even though the CORS headers on a data page give the assurance that the data is not confidential, the browser blocks access to the data on the grounds that the data could be tampered with or spied on and this is something which an HTTP script should guarantee against.

The obvious solution is to server the original script over HTTP.

A more complex solution is to provide an general proxy in the origin sever which allows the client to access the entire web via the a proxy.   This of course opens up concerns about the open proxy being used  by attacking code, unless a way is found of ensuring that the request comes from the original script. To move in this direction means that instead of the user having control of an application which is their agent, they rely on the server to perform the web accesses on their behalf.  The possibility of the user being abused in terms of privacy is obviously increased in this model.  In this model the client-server model of the web has been broken, significantly disadvantaging the user.

This needs to be explained in any document  suggests moving to HTTPS is a good idea.

**Comment by mikewest** [comment] 2014-12-26 12:01
Pointing to the Mixed Content spec (https://w3c.github.io/webappsec/specs/mixedcontent/) is probably a reasonable way to talk about these sorts of concerns.

One note: the practical thrust of your argument seems to be that wide-open CORS headers should allow sites to load data into a secure context from insecure sources, as those headers give "the assurance that the data is not confidential". Those headers do not, however, give any assurance that a particular user's _access_ of that data is not, or should not be considered confidential. The threat model which mixed content blocking is meant to address includes security concerns relating to authenticated data, but _also_ privacy concerns relating to the confidentiality of those requests.

WebAppSec plans to bring Mixed Content to you/your delegates early next year to request a transition from WD to CR. I'm sure we'd be happy to discuss/address your concerns explicitly in that document if you wouldn't mind raising them on public-webappsec@ for discussion.

**Comment by mnot** [comment] 2014-12-26 12:46
Regarding making it an open proxy -- usually, this is addressed by constraining the resources available through the proxy; e.g., authenticate the user, look up the resources that the user has access to (or has configured), and then only allow those requests.

I agree with Mike that the spec to address this in specifically is Mixed Content. 

In this document, I think what's needed here is an expansion around this text:

> Simultaneously, reducing the costs of using encryption should be a continuing area of focus
>         for the W3C. In particular, features that change behavior based upon the URL scheme
>         ("http://" to "https://") should be examined to see if these differences can either be
>         eliminated or controlled by authors, provided that there is no loss of security or
>         surprising changes in behavior. For example, the [[referrer-policy]] specification is
>         offering more control over the Referer HTTP header, as part of [[CSP2]]. The TAG encourages
>         work to identify similar areas of friction and potential mitigations.

I'll work on it.

**Comment by timbl** [comment] 2014-12-29 09:15
<blockquote>Regarding making it an open proxy -- usually, this is addressed by constraining the resources available through the proxy; e.g., authenticate the user, look up the resources that the user has access to (or has configured), and then only allow those requests.</blockquote>

In the case of an open data mashup of open data, there is no authentication.   Everyone can run the script, the script needs access to any open data on the web.

**Comment by timbl** [comment] 2014-12-29 09:25
@mikewest, 

<blockquote>
WebAppSec plans to bring Mixed Content to you/your delegates early next year to request a transition from WD to CR. I'm sure we'd be happy to discuss/address your concerns explicitly in that document if you wouldn't mind raising them on public-webappsec@ for discussion.
</blockquote>

While I am happy to send input to that discussion, it won't make the problem go away for users or for this document until the browser code is changed.  With current browsers today, you can't use HTTPS for data mashup scripts, and the document needs to warn you of that. 

This document could say something along the lines of "The blocking of HTTP access by XHR in HTTPS-sourced scripts is a bug and we expect it to be fixed by webapps and the browser vendors, and our recommendation of HTTPs everythere is contingent on that fix."  I suppose.

**Comment by mikewest** [comment] 2014-12-29 14:20
@timbl: Sounds like we'll have an interesting thread on public-webappsec@ soon! :)

> In the case of an open data mashup of open data, there is no authentication. Everyone
> can run the script, the script needs access to any open data on the web.

Note that anyone in-between you and the insecure resource can inject whatever headers she likes, thereby "opening" data that isn't, in fact, meant to be open. Relying on CORS headers to dictate terms of data access relies entirely upon integrity and authentication of the transport layer upon which the data travels.

> This document could say something along the lines of "The blocking of HTTP access by XHR
> in HTTPS-sourced scripts is a bug and we expect it to be fixed by webapps and the browser
> vendors, and our recommendation of HTTPs everywhere is contingent on that fix." I suppose.

As I noted in an earlier comment regarding confidentiality, I don't think this behavior is a bug. In fact, I think it's likely that browser code will be updated in the opposite direction: tightening rather than loosening mixed content checks.

**Comment by marcoscaceres** [comment] 2014-12-30 02:01
Agree with @mikewest. This is a feature of browsers, not a bug.

**Comment by konklone** [comment] 2015-01-04 10:13
Hey @timbl, I'm really glad you're bringing up open data and mashups as a use case here. It's something I care a lot about.

I've worked in the open data field professionally for the last 6 years -- I spent 5 of those at the [Sunlight Foundation](https://sunlightfoundation.com), helped create a [successful open data community](https://github.com/unitedstates), and now work at a US government team, [18F](https://18f.gsa.gov), where [open source](https://github.com/18F/open-source-policy) and [open data](https://18f.gsa.gov/2014/12/18/a-complete-list-of-gov-domains/) are its standard operating procedures. I've written a lot of open data scrapers in my day, and made a lot of mashups and search engines.

It's from this background that I firmly believe that open data over plain HTTP is completely unacceptable.

Any data that's important enough to call "open data", that we think there's value in people, businesses, and civil society depending on -- is important enough that we should demand that it's provided over a secure and private connection.

This is why Gov.UK [requires HTTPS for government services](https://www.gov.uk/service-manual/domain-names/https.html), and why 18F [will only build .gov sites that use HTTPS](https://18f.gsa.gov/2014/11/13/why-we-use-https-in-every-gov-website-we-make/). It's why Sunlight ensures [its legislative APIs are encrypted](https://sunlightfoundation.com/blog/2014/01/28/encrypting-our-congress-api-and-protecting-your-location/), and why HTTPS is [increasingly](https://twitter.com/waldojaquith/status/551089956870193152) the [priority](https://twitter.com/JoshData/status/378616437020971008) of the open data [community](https://twitter.com/courtlistener/status/354388742569598977).

"Open data" is a broad term, covering services and information that touch every part of our lives. No ISP, cafe, or government should be able to use HTTP requests for open data to [identify someone's location](https://www.propublica.org/article/spy-agencies-probe-angry-birds-and-other-apps-for-personal-data), [profile their health](http://www.washingtonpost.com/blogs/the-switch/wp/2014/11/07/federal-sites-leaked-the-locations-of-people-seeking-aids-services-for-years/), or [track their browsing activity](https://www.eff.org/deeplinks/2014/11/verizon-x-uidh) -- or to sell the metadata to someone who will. Open data on the web has to serve the public's interest, and HTTPS is the most basic way to achieve that.

Besides privacy, if a person or a service is to _depend_ on open data -- something we all want to see more of -- it's got to be over a secure connection. As a concrete example: in my time at Sunlight, I developed an [open data IFTTT channel](https://ifttt.com/sunlightfoundation) that fires when new laws are signed and votes are scheduled. Channels are implemented as web APIs that IFTTT regularly queries for updates. IFTTT _required_ that Sunlight's channel -- that all IFTTT channels -- be provided over HTTPS.

And why wouldn't they? For its users' sake, IFTTT is depending on Sunlight's information to be reliable, and for Sunlight's data on government actions to appear only when the government has really taken action. It would be completely foolhardy for people or companies to let the channel affect their advocacy work or their Christmas lights if the communication weren't handled over something as basic as a secure connection.

I know (believe me) that there's lots of open data only available over HTTP, especially in the government. That's not a reality to accommodate, it's a fixable tragedy. A W3C working group shouldn't have to accommodate this with a disclaimer, and browsers certainly shouldn't relax mixed content policy to make it easier on open data publishers to keep getting away with not meeting basic responsibilities.

If you feel strongly that open data is a key part of the web's future, and a boon to the public and to the private sector -- and it's clear that you do -- then you should be pushing open data publishers big and small, in the UK and abroad, to get their act together and install an HTTPS certificate already.

**Comment by mnot** [comment] 2015-01-12 14:21
I think this is addressed in current text. Tim, if you have a concern, please reopen.

**Closed as completed by mnot** 2015-01-12 14:21 UTC

**Comment by timbl** [comment] 2015-02-25 15:37
Well, @konklone, your arguments are for encryption and for authentication but not specifically for there being an 's' in the URL scheme.     And they apply to open data just as they apply to any content.    See the public-webaps@w3.org thread.

**Comment by mikewest** [comment] 2015-02-26 06:53
The extra "s" in the URL scheme separates the origins of the secure and insecure resources. This is valuable, as it prevents data transferred over an insecure connection from accessing (or tainting) data which was transferred over a secure connection.

**Comment by konklone** [comment] 2015-02-26 17:19
@hillbrad's response on the list, pointing to the proposed `upgrade-insecure-resources` directive and the CSP Pinning header, seem like the way to go for large blocks of legacy links:
- https://w3c.github.io/webappsec/specs/upgrade/
- https://w3c.github.io/webappsec/specs/csp-pinning/

This does still obligate the domain owner to install a valid HTTPS certificate for those resources, and to add the CSP header(s). For some content owners, that's a much smaller burden than installing the certificate _and_ going back and updating all the content.

Adding (and ideally, preloading) HSTS for the domain would also help for other contexts, but since [HSTS is performed _after_ mixed-content checking](https://lists.w3.org/Archives/Public/public-webappsec/2014Nov/0307.html) a CSP policy is the way to go when it's mixed content
